#!/bin/bash
# =============================================================================
# SECURITY AUDIT — Tiny Seed Farm OS
# =============================================================================
# Three-pass audit per docs/system/AUDIT_PROTOCOL.md
# Run weekly: ./scripts/security-audit.sh
# =============================================================================

set -e

REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null || echo ".")
REPORT_DATE=$(date +%Y-%m-%d)
REPORT_FILE="${REPO_ROOT}/AUDIT_REPORT_${REPORT_DATE}.md"

echo "═══════════════════════════════════════════════════════════"
echo " Tiny Seed Farm OS — Security Audit"
echo " Date: ${REPORT_DATE}"
echo "═══════════════════════════════════════════════════════════"
echo ""

# Initialize report
cat > "$REPORT_FILE" << EOF
# Security Audit Report — ${REPORT_DATE}

**Generated by:** \`scripts/security-audit.sh\`
**Protocol:** \`docs/system/AUDIT_PROTOCOL.md\`

---

EOF

# ═════════════════════════════════════════════════════════════════
# PASS 1: CONTEXT BUILD
# ═════════════════════════════════════════════════════════════════
echo "══ PASS 1: Context Build ══"
echo ""

HTML_COUNT=$(find "$REPO_ROOT" -maxdepth 2 -name "*.html" -not -path "*/node_modules/*" -not -path "*/.git/*" | wc -l | tr -d ' ')
JS_COUNT=$(find "$REPO_ROOT" -maxdepth 3 -name "*.js" -not -path "*/node_modules/*" -not -path "*/.git/*" -not -path "*/tinypm/*" | wc -l | tr -d ' ')
APPS_SCRIPT_COUNT=$(find "$REPO_ROOT/apps_script" -name "*.js" -o -name "*.html" 2>/dev/null | wc -l | tr -d ' ')

echo "  HTML files: ${HTML_COUNT}"
echo "  JS files: ${JS_COUNT}"
echo "  Apps Script files: ${APPS_SCRIPT_COUNT}"

# Count API endpoints (fetch calls)
FETCH_COUNT=$(grep -rl 'fetch(' "$REPO_ROOT"/*.html "$REPO_ROOT"/web_app/*.html "$REPO_ROOT"/web_app/*.js 2>/dev/null | wc -l | tr -d ' ')
echo "  Files with fetch() calls: ${FETCH_COUNT}"

# Count form submissions
FORM_COUNT=$(grep -rl '<form' "$REPO_ROOT"/*.html "$REPO_ROOT"/web_app/*.html 2>/dev/null | wc -l | tr -d ' ')
echo "  Files with <form> elements: ${FORM_COUNT}"

# API action parameters
ACTION_COUNT=$(grep -roh "action=['\"][a-zA-Z]*['\"]" "$REPO_ROOT"/*.html "$REPO_ROOT"/web_app/*.html "$REPO_ROOT"/web_app/*.js 2>/dev/null | sort -u | wc -l | tr -d ' ')
echo "  Unique API action parameters: ${ACTION_COUNT}"

cat >> "$REPORT_FILE" << EOF
## Pass 1: Context Build

| Metric | Count |
|--------|-------|
| HTML files | ${HTML_COUNT} |
| JS files | ${JS_COUNT} |
| Apps Script files | ${APPS_SCRIPT_COUNT} |
| Files with fetch() | ${FETCH_COUNT} |
| Files with <form> | ${FORM_COUNT} |
| Unique API actions | ${ACTION_COUNT} |

EOF

echo ""
echo "  ✅ Pass 1 complete"
echo ""

# ═════════════════════════════════════════════════════════════════
# PASS 2: SECURITY SWEEP
# ═════════════════════════════════════════════════════════════════
echo "══ PASS 2: Security Sweep ══"
echo ""

P0_COUNT=0
P1_COUNT=0
P2_COUNT=0
P3_COUNT=0
FINDINGS=""

# --- 2A: Hardcoded Secrets ---
echo "  [2A] Scanning for hardcoded secrets..."
MAPS_KEY_FILES=$(grep -rl 'AIzaSy[A-Za-z0-9_-]\{30,\}' "$REPO_ROOT"/*.html "$REPO_ROOT"/web_app/*.html "$REPO_ROOT"/web_app/*.js 2>/dev/null | grep -v 'api-config.js' || true)
MAPS_KEY_COUNT=$(echo "$MAPS_KEY_FILES" | grep -c '.' 2>/dev/null || echo "0")
if [ "$MAPS_KEY_COUNT" -gt 0 ]; then
    FINDINGS="${FINDINGS}\n### P0: Hardcoded Google Maps API Keys\n\n\`\`\`\n${MAPS_KEY_FILES}\n\`\`\`\n\n**Fix:** Move to \`api-config.js\` as \`TINY_SEED_API.GOOGLE_MAPS_KEY\`\n"
    P0_COUNT=$((P0_COUNT + MAPS_KEY_COUNT))
    echo "    ❌ ${MAPS_KEY_COUNT} file(s) with hardcoded Google Maps keys"
else
    echo "    ✅ No hardcoded Maps keys"
fi

# --- 2B: innerHTML with dynamic data ---
echo "  [2B] Scanning innerHTML usage..."
INNERHTML_TOTAL=$(grep -rn '\.innerHTML\s*=' "$REPO_ROOT"/*.html "$REPO_ROOT"/web_app/*.html "$REPO_ROOT"/web_app/*.js 2>/dev/null | grep -v '^\s*//' | wc -l | tr -d ' ')
echo "    ⚠️  ${INNERHTML_TOTAL} innerHTML assignments found across codebase"
if [ "$INNERHTML_TOTAL" -gt 0 ]; then
    FINDINGS="${FINDINGS}\n### P1: innerHTML Usage (${INNERHTML_TOTAL} instances)\n\nEach is a potential XSS vector if fed Sheets/API data.\n\n**Fix:** Use \`.textContent\` for text, or sanitize with DOMPurify.\n"
    P1_COUNT=$((P1_COUNT + 1))
fi

# --- 2C: eval/document.write/setTimeout(string) ---
echo "  [2C] Scanning banned patterns..."
EVAL_COUNT=$(grep -rn '[^a-zA-Z]eval(' "$REPO_ROOT"/*.html "$REPO_ROOT"/web_app/*.html "$REPO_ROOT"/web_app/*.js 2>/dev/null | grep -v '^\s*//' | grep -v 'node_modules' | wc -l | tr -d ' ')
DOCWRITE_COUNT=$(grep -rn 'document\.write(' "$REPO_ROOT"/*.html "$REPO_ROOT"/web_app/*.html 2>/dev/null | wc -l | tr -d ' ')
NEW_FUNC_COUNT=$(grep -rn 'new Function(' "$REPO_ROOT"/*.html "$REPO_ROOT"/web_app/*.html "$REPO_ROOT"/web_app/*.js 2>/dev/null | grep -v '^\s*//' | wc -l | tr -d ' ')

echo "    eval(): ${EVAL_COUNT} | document.write(): ${DOCWRITE_COUNT} | new Function(): ${NEW_FUNC_COUNT}"

if [ "$EVAL_COUNT" -gt 0 ]; then
    EVAL_DETAILS=$(grep -rn '[^a-zA-Z]eval(' "$REPO_ROOT"/*.html "$REPO_ROOT"/web_app/*.html "$REPO_ROOT"/web_app/*.js 2>/dev/null | grep -v '^\s*//' | head -10)
    FINDINGS="${FINDINGS}\n### P0: eval() Usage (${EVAL_COUNT} instances)\n\n\`\`\`\n${EVAL_DETAILS}\n\`\`\`\n"
    P0_COUNT=$((P0_COUNT + EVAL_COUNT))
fi

if [ "$DOCWRITE_COUNT" -gt 0 ]; then
    FINDINGS="${FINDINGS}\n### P2: document.write() Usage (${DOCWRITE_COUNT} instances)\n\nMostly print contexts. Review for main-page usage.\n"
    P2_COUNT=$((P2_COUNT + 1))
fi

# --- 2D: SRI hash coverage ---
echo "  [2D] Checking SRI hash coverage..."
CDN_TOTAL=$(grep -rn '<script[^>]*src="https://' "$REPO_ROOT"/*.html "$REPO_ROOT"/web_app/*.html 2>/dev/null | grep -v 'fonts.googleapis' | grep -v 'maps.googleapis' | grep -v 'apis.google.com' | wc -l | tr -d ' ')
CDN_WITH_SRI=$(grep -rn '<script[^>]*src="https://' "$REPO_ROOT"/*.html "$REPO_ROOT"/web_app/*.html 2>/dev/null | grep -v 'fonts.googleapis' | grep -v 'maps.googleapis' | grep 'integrity=' | wc -l | tr -d ' ')
CDN_MISSING=$((CDN_TOTAL - CDN_WITH_SRI))

echo "    CDN scripts: ${CDN_TOTAL} total, ${CDN_WITH_SRI} with SRI, ${CDN_MISSING} missing"

if [ "$CDN_MISSING" -gt 0 ]; then
    FINDINGS="${FINDINGS}\n### P2: Missing SRI Hashes (${CDN_MISSING}/${CDN_TOTAL} scripts)\n\n**Fix:** Generate at https://www.srihash.org/ and add \`integrity\` attribute.\n"
    P2_COUNT=$((P2_COUNT + 1))
fi

# --- 2E: CSP meta tag coverage ---
echo "  [2E] Checking CSP coverage..."
HTML_FILES=$(find "$REPO_ROOT" -maxdepth 1 -name "*.html" -not -path "*/.git/*"; find "$REPO_ROOT/web_app" -maxdepth 1 -name "*.html" 2>/dev/null)
CSP_TOTAL=0
CSP_PRESENT=0
for f in $HTML_FILES; do
    CSP_TOTAL=$((CSP_TOTAL + 1))
    if grep -q 'Content-Security-Policy' "$f" 2>/dev/null; then
        CSP_PRESENT=$((CSP_PRESENT + 1))
    fi
done
CSP_MISSING=$((CSP_TOTAL - CSP_PRESENT))

echo "    HTML files: ${CSP_TOTAL} total, ${CSP_PRESENT} with CSP, ${CSP_MISSING} missing"

if [ "$CSP_MISSING" -gt 0 ]; then
    FINDINGS="${FINDINGS}\n### P2: Missing CSP Meta Tags (${CSP_MISSING}/${CSP_TOTAL} files)\n\n**Fix:** Add \`<meta http-equiv=\"Content-Security-Policy\" content=\"...\">\` to all HTML files.\n"
    P2_COUNT=$((P2_COUNT + 1))
fi

# --- 2F: Token in URL parameters ---
echo "  [2F] Checking token handling..."
TOKEN_URL_COUNT=$(grep -rn 'token=' "$REPO_ROOT"/*.html "$REPO_ROOT"/web_app/*.html 2>/dev/null | grep -v '^\s*//' | grep -v 'csrf' | wc -l | tr -d ' ')
echo "    Files passing tokens in URLs: ${TOKEN_URL_COUNT}"

if [ "$TOKEN_URL_COUNT" -gt 5 ]; then
    FINDINGS="${FINDINGS}\n### P3: Tokens in URL Parameters (${TOKEN_URL_COUNT} instances)\n\nURL tokens appear in browser history and server logs.\n"
    P3_COUNT=$((P3_COUNT + 1))
fi

# --- 2G: Run existing audit scripts if available ---
echo "  [2G] Running existing audit suite..."
AUDIT_DIR="$REPO_ROOT/scripts/audit"
if [ -d "$AUDIT_DIR" ] && [ -x "$AUDIT_DIR/run-full-audit.sh" ]; then
    echo "    Running scripts/audit/run-full-audit.sh (output suppressed)..."
    "$AUDIT_DIR/run-full-audit.sh" > /tmp/audit_suite_output_$$.txt 2>&1 || true
    AUDIT_SUITE_RESULT=$(tail -5 /tmp/audit_suite_output_$$.txt)
    echo "    Suite completed."
    rm -f /tmp/audit_suite_output_$$.txt
else
    echo "    ⚠️  Audit suite not found or not executable"
fi

# Write Pass 2 to report
cat >> "$REPORT_FILE" << EOF
## Pass 2: Security Sweep

### Summary

| Severity | Count |
|----------|-------|
| P0 (Critical) | ${P0_COUNT} |
| P1 (High) | ${P1_COUNT} |
| P2 (Medium) | ${P2_COUNT} |
| P3 (Low) | ${P3_COUNT} |

### Detailed Findings
$(echo -e "$FINDINGS")

EOF

echo ""
echo "  ✅ Pass 2 complete — P0:${P0_COUNT} P1:${P1_COUNT} P2:${P2_COUNT} P3:${P3_COUNT}"
echo ""

# ═════════════════════════════════════════════════════════════════
# PASS 3: RED TEAM CHECKLIST
# ═════════════════════════════════════════════════════════════════
echo "══ PASS 3: Red Team Checklist ══"
echo ""

cat >> "$REPORT_FILE" << 'EOF'
## Pass 3: Red Team Checklist

Manual adversarial testing — complete these checks:

### Price / Quantity Manipulation
- [ ] Open DevTools on any order page → modify price in DOM → submit → verify server rejects
- [ ] Submit negative quantity via curl to Apps Script → verify server validates
- [ ] Submit quantity=0 → verify server rejects
- [ ] Submit quantity exceeding stock → verify server rejects

### Direct API Forgery
- [ ] `curl -X POST [APPS_SCRIPT_URL] -d '{"action":"placeOrder","items":[{"id":"test","qty":1,"price":0.01}]}'` → verify server looks up real price
- [ ] Send request with invalid `action` parameter → verify whitelist rejects
- [ ] Send request with missing required fields → verify graceful error

### Formula Injection
- [ ] Enter `=IMPORTRANGE(...)` as a customer name → verify ' prefix added before Sheets write
- [ ] Enter `=IMAGE("http://evil.com/tracker.gif")` as a variety name → verify sanitized
- [ ] Enter `=HYPERLINK("http://evil.com","Click")` in any text field → verify sanitized

### XSS via Sheets Data
- [ ] Add `<script>alert(1)</script>` as a crop variety in the spreadsheet → verify not executed on page load
- [ ] Add `<img onerror=alert(1) src=x>` as a customer name → verify not rendered as HTML
- [ ] Check all innerHTML assignments render Sheets data safely

### Authentication / Token Security
- [ ] Copy a magic link token → use in different browser → verify behavior
- [ ] Modify token in URL → verify server rejects invalid tokens
- [ ] Check if expired tokens are properly rejected

### Infrastructure
- [ ] Verify GitHub Pages "Enforce HTTPS" is enabled
- [ ] Check Apps Script sharing — only Todd should have editor access
- [ ] Review Apps Script triggers for unexpected entries
- [ ] Test `Access-Control-Allow-Origin: *` — verify server-side validation compensates

EOF

echo "  Red team checklist written to report."
echo "  ✅ Pass 3 complete"
echo ""

# ═════════════════════════════════════════════════════════════════
# GITLEAKS CHECK (Gate 3 — Monthly)
# ═════════════════════════════════════════════════════════════════
echo "══ OPTIONAL: Gitleaks Check ══"
if command -v gitleaks &> /dev/null; then
    echo "  Running gitleaks..."
    gitleaks detect --source "$REPO_ROOT" --no-git 2>/tmp/gitleaks_output_$$.txt || true
    GITLEAKS_RESULT=$(cat /tmp/gitleaks_output_$$.txt)
    echo "  $GITLEAKS_RESULT"
    echo -e "\n## Gitleaks Results\n\n\`\`\`\n${GITLEAKS_RESULT}\n\`\`\`\n" >> "$REPORT_FILE"
    rm -f /tmp/gitleaks_output_$$.txt
else
    echo "  ⚠️  gitleaks not installed. Install with: brew install gitleaks"
    echo -e "\n## Gitleaks\n\n⚠️ Not installed. Run: \`brew install gitleaks\`\n" >> "$REPORT_FILE"
fi

# ═════════════════════════════════════════════════════════════════
# FINAL SUMMARY
# ═════════════════════════════════════════════════════════════════
echo ""
echo "═══════════════════════════════════════════════════════════"
echo " AUDIT COMPLETE"
echo "═══════════════════════════════════════════════════════════"

TOTAL_ISSUES=$((P0_COUNT + P1_COUNT + P2_COUNT + P3_COUNT))

if [ "$P0_COUNT" -gt 0 ]; then
    echo " ❌ DEPLOYMENT BLOCKED — ${P0_COUNT} P0 (Critical) issues found"
    VERDICT="FAIL — Deployment Blocked"
elif [ "$P1_COUNT" -gt 0 ]; then
    echo " ⚠️  FIX BEFORE NEXT PUSH — ${P1_COUNT} P1 (High) issues"
    VERDICT="WARN — Fix Before Push"
else
    echo " ✅ PASS — No blocking issues"
    VERDICT="PASS"
fi

echo ""
echo " Total: P0:${P0_COUNT} P1:${P1_COUNT} P2:${P2_COUNT} P3:${P3_COUNT}"
echo " Report: ${REPORT_FILE}"
echo "═══════════════════════════════════════════════════════════"

cat >> "$REPORT_FILE" << EOF

---

## Verdict: ${VERDICT}

| Severity | Count |
|----------|-------|
| **P0 (Critical)** | ${P0_COUNT} |
| **P1 (High)** | ${P1_COUNT} |
| **P2 (Medium)** | ${P2_COUNT} |
| **P3 (Low)** | ${P3_COUNT} |
| **Total** | ${TOTAL_ISSUES} |

*Generated by \`scripts/security-audit.sh\` on ${REPORT_DATE}*
*Protocol: \`docs/system/AUDIT_PROTOCOL.md\`*
EOF
