#!/bin/bash

# Tiny Seed Farm - Telegram Bot Setup Script
# This script helps configure the Telegram bot

echo "=============================================="
echo "  Tiny Seed Farm - Telegram Bot Setup"
echo "=============================================="
echo ""

# Check if Node.js is installed
if ! command -v node &> /dev/null; then
    echo "Error: Node.js is not installed."
    echo "Please install Node.js v16 or higher from: https://nodejs.org"
    exit 1
fi

NODE_VERSION=$(node -v | cut -d'v' -f2 | cut -d'.' -f1)
if [ "$NODE_VERSION" -lt 16 ]; then
    echo "Error: Node.js v16+ required. You have $(node -v)"
    exit 1
fi

echo "Node.js $(node -v) detected"
echo ""

# Check if .env exists
if [ -f ".env" ]; then
    echo "Existing .env file found."
    read -p "Do you want to reconfigure? (y/N): " RECONFIG
    if [ "$RECONFIG" != "y" ] && [ "$RECONFIG" != "Y" ]; then
        echo "Keeping existing configuration."
        echo ""
        read -p "Install dependencies and start bot? (Y/n): " START
        if [ "$START" != "n" ] && [ "$START" != "N" ]; then
            npm install
            npm start
        fi
        exit 0
    fi
fi

echo ""
echo "Step 1: Create your Telegram Bot"
echo "--------------------------------"
echo "1. Open Telegram and search for @BotFather"
echo "2. Send /newbot and follow the prompts"
echo "3. Copy the bot token BotFather gives you"
echo ""
read -p "Paste your bot token: " BOT_TOKEN

if [ -z "$BOT_TOKEN" ]; then
    echo "Error: Bot token is required"
    exit 1
fi

echo ""
echo "Step 2: Get your Chat ID"
echo "------------------------"
echo "Options:"
echo "  A) Message @userinfobot on Telegram to get your ID"
echo "  B) Leave blank and the bot will tell you when you message it"
echo ""
read -p "Enter your Chat ID (or press Enter to skip): " CHAT_ID

# Create .env file
cat > .env << EOF
# Telegram Bot Configuration
# Generated by setup script on $(date)

# Your Telegram Bot Token
TELEGRAM_BOT_TOKEN=$BOT_TOKEN

# Your Telegram Chat ID
OWNER_CHAT_ID=$CHAT_ID

# Google Apps Script API URL
API_URL=https://script.google.com/macros/s/AKfycbwS36-nKIb1cc6l7AQmnM24Ynx_yluuN-_ZMZr5VRGK7ZpqqemMvXGArvzKS3TlHYCb/exec

# Polling interval for checking responses (milliseconds)
POLL_INTERVAL=5000

# Enable verbose logging (true/false)
VERBOSE=false
EOF

echo ""
echo ".env file created successfully!"
echo ""

if [ -z "$CHAT_ID" ]; then
    echo "NOTE: You didn't set a Chat ID."
    echo "When you message the bot, it will show you your Chat ID."
    echo "Then edit .env and add your OWNER_CHAT_ID."
    echo ""
fi

# Install dependencies
echo "Installing dependencies..."
npm install

echo ""
echo "=============================================="
echo "  Setup Complete!"
echo "=============================================="
echo ""
echo "To start the bot:"
echo "  npm start"
echo ""
echo "For verbose logging:"
echo "  npm run dev"
echo ""
echo "To run in background with PM2:"
echo "  npm install -g pm2"
echo "  pm2 start bot.js --name tiny-seed-bot"
echo ""

read -p "Start the bot now? (Y/n): " START_NOW
if [ "$START_NOW" != "n" ] && [ "$START_NOW" != "N" ]; then
    npm start
fi
