import { chromium } from 'playwright';
const b=await chromium.launch({headless:true});
const p=await (await b.newContext({userAgent:'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/154.0.0.0 Safari/537.36',viewport:{width:1500,height:1400}})).newPage();
await p.goto('https://www.partstree.com/search?search='+encodeURIComponent(process.argv[2])+'&tab=parts',{waitUntil:'domcontentloaded',timeout:45000});
await p.waitForTimeout(5000);
const t=await p.evaluate(()=>document.body.innerText);
const L=t.split('\n').map(s=>s.trim()).filter(Boolean);
const i=L.findIndex(s=>/^Results:/.test(s));
console.log(L.slice(i>=0?i:0,(i>=0?i:0)+45).join('\n'));
await b.close();
